### ISSUE TITLE
Empty project

### ISSUE THREAD

**Issue by VadimsMalickis** [GRebuks/grebuks.github.io#1]
1. Atgādiniet lūdzu kā Jums sanāca 8 par oktobri?
Varat vienkārši uzrakstīt komentāru šeit.
2. Un protams vajadzētu ielādēt projektu uz Jūsu repo

**Comment by GRebuks** [comment]
Par oktobri tika ielikts 8 par izveidotu lapas galveni (header) un iesāktu galvenā satura dizainu.
Kopš iepriekšējā vērtējuma dizains nedaudz mainījies, kā arī mājaslapā tiek izmantots PHP, tāpēc lapu nevarēs atvērt izmantojot GitHub Pages, jo GitHub Pages neatbalsta servera puses valodas kā PHP.

P.S. Atvainojos par vēlo atbildi, nepamanīju atvērto issue.

**Comment by VadimsMalickis** [comment]
Ok paldies. Mēģinašu palaist Jūsu php projektu uz savā izstrādes vidē. Un es pats mazliet nepareizi biju atveris Issue.

**Comment by VadimsMalickis** [comment]
Par projekta palaišanu.
Lai patestētu formas sūtišanas funkcionalitāti, ir nepieciešama projekta datubāze.
Mācibu kontekstā parasti uztaisa tā saucamo "sql dump" un iekomito to git repozitorijā to.

https://dev.mysql.com/doc/refman/5.7/en/mysqldump-sql-format.html

@GRebuks

**Comment by GRebuks** [comment]
Jaunākajā repozitorija commit ievietoju "sql dump" iekš mapes 'db'. Iztestēju sql dump importēšanas procesu un uz mana datora formas funkcionalitāte strādā. Rezultātā ievadītai informācijai iekš formas būtu vienkārši jāsaglabājas `portfolio_grdp31` datubāzes `contact` tabulā.

Ja rodas kādas problēmas, lūdzu dodiet ziņu.
